version: "3"
services:
  postgres:
    image: "postgres:latest"
  redis:
    image: "redis:latest"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: "./server"
    volumes:
      - /app/node_modules # leave as is
      - ./server:/app # copy everything else
    environment:
      # look at hub.docker to find info on defaults
      - REDIS_HOST=redis # from redis service
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPOR=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: "./client"
    volumes:
      - "/app/node_modules"
      - "./client:/app"
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: "./worker"
    volumes:
      - "/app/node_modules"
      - "./worker:/app"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
